# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('autoid', models.AutoField(db_column='autoID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('autoid', models.AutoField(db_column='autoID', primary_key=True, serialize=False)),
                ('userid', models.CharField(db_column='userID', max_length=64)),
                ('userpsd', models.CharField(db_column='userPsd', max_length=64)),
                ('name', models.CharField(max_length=16)),
                ('sex', models.CharField(blank=True, null=True, max_length=16)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('hometown', models.CharField(blank=True, null=True, max_length=64)),
                ('nation', models.CharField(blank=True, null=True, max_length=64)),
                ('party', models.CharField(blank=True, null=True, max_length=64)),
                ('photo', models.FileField(upload_to='personalupload/')),
                ('department', models.CharField(max_length=64)),
                ('job', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('postcode', models.IntegerField()),
                ('gradschool', models.CharField(db_column='gradSchool', max_length=64)),
                ('gradtime', models.DateField(db_column='gradTime')),
                ('major', models.CharField(max_length=64)),
                ('health', models.CharField(blank=True, null=True, max_length=64)),
                ('highestdegree', models.CharField(db_column='highestDegree', max_length=64)),
                ('techtitle', models.CharField(blank=True, null=True, db_column='techTitle', max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone_depart', models.IntegerField(blank=True, null=True)),
                ('phone_personal', models.IntegerField()),
                ('phone_home', models.IntegerField(blank=True, null=True)),
                ('phone_fax', models.IntegerField(blank=True, null=True)),
                ('now_major', models.CharField(max_length=64)),
                ('speciality', models.CharField(blank=True, null=True, max_length=64)),
                ('workyears', models.IntegerField(blank=True, db_column='workYears', null=True)),
                ('language', models.CharField(blank=True, null=True, max_length=64)),
                ('language_level', models.CharField(blank=True, null=True, max_length=64)),
                ('description_job', models.CharField(blank=True, null=True, db_column='Description_job', max_length=255)),
                ('description_works', models.CharField(blank=True, null=True, db_column='Description_works', max_length=255)),
                ('isverify', models.IntegerField(blank=True, db_column='isVerify', null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organzation',
            fields=[
                ('autoid', models.AutoField(db_column='autoID', primary_key=True, serialize=False)),
                ('orgid', models.IntegerField(db_column='orgID')),
                ('orgpsd', models.CharField(db_column='orgPsd', max_length=45)),
                ('orgname', models.CharField(db_column='orgName', max_length=45)),
                ('orgcontact', models.CharField(db_column='orgContact', max_length=45)),
                ('orgphone', models.CharField(db_column='orgPhone', max_length=45)),
                ('orgfax', models.CharField(blank=True, null=True, db_column='orgFax', max_length=45)),
                ('orgaddress', models.CharField(blank=True, null=True, db_column='orgAddress', max_length=45)),
                ('orgpostcode', models.CharField(blank=True, null=True, db_column='orgPostcode', max_length=45)),
                ('orgemail', models.CharField(blank=True, null=True, db_column='orgEmail', max_length=45)),
                ('orglrname', models.CharField(blank=True, null=True, db_column='orgLRName', max_length=45)),
                ('orglrbirthday', models.DateField(blank=True, db_column='orgLRBirthday', null=True)),
                ('orglrtitle', models.CharField(blank=True, null=True, db_column='orgLRTitle', max_length=45)),
                ('orglreducation', models.CharField(blank=True, null=True, db_column='orgLREducation', max_length=45)),
                ('orglrphone', models.CharField(blank=True, null=True, db_column='orgLRPhone', max_length=45)),
                ('orglrhomephone', models.CharField(blank=True, null=True, db_column='orgLRHomephoe', max_length=45)),
                ('orglremail', models.CharField(blank=True, null=True, db_column='orgLREmail', max_length=45)),
                ('orgrname', models.CharField(blank=True, null=True, db_column='orgRName', max_length=45)),
                ('orgrbirthday', models.CharField(blank=True, null=True, db_column='orgRBirthday', max_length=45)),
                ('orgrtitle', models.CharField(blank=True, null=True, db_column='orgRTitle', max_length=45)),
                ('orgreducation', models.CharField(blank=True, null=True, db_column='orgREducation', max_length=45)),
                ('orgrphone', models.CharField(blank=True, null=True, db_column='orgRPhone', max_length=45)),
                ('orgrhomephone', models.CharField(blank=True, null=True, db_column='orgRHomephoe', max_length=45)),
                ('orgremail', models.CharField(blank=True, null=True, db_column='orgREmail', max_length=45)),
                ('orgresume', models.FileField(upload_to='orgupload/')),
                ('orgdetail', models.TextField(blank=True, db_column='orgDetail', null=True)),
                ('establishtime', models.DateField(blank=True, db_column='establishTime', null=True)),
                ('totalworkers', models.IntegerField(blank=True, db_column='totalWorkers', null=True)),
                ('techworkers', models.IntegerField(blank=True, db_column='techWorkers', null=True)),
                ('hightitle', models.IntegerField(blank=True, null=True)),
                ('midletitle', models.IntegerField(blank=True, null=True)),
                ('revenueoneyearago', models.IntegerField(blank=True, db_column='revenueOneyearAgo', null=True)),
                ('revenuetwoyearago', models.IntegerField(blank=True, db_column='revenueTwoyearAgo', null=True)),
                ('revenuethreeyearago', models.IntegerField(blank=True, db_column='revenueThreeyearAgo', null=True)),
                ('mainproduct', models.CharField(blank=True, null=True, db_column='mainProduct', max_length=255)),
                ('wanttitle', models.CharField(blank=True, null=True, db_column='wantTitle', max_length=255)),
                ('isagree', models.CharField(blank=True, null=True, db_column='isAgree', max_length=45)),
                ('isverfity', models.CharField(blank=True, null=True, db_column='isVerfity', max_length=45)),
            ],
            options={
                'db_table': 'organzation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('autoid', models.IntegerField(db_column='autoID', primary_key=True, serialize=False)),
                ('memberid', models.IntegerField(db_column='memberID')),
                ('units', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=64)),
                ('tel', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('address', models.CharField(max_length=64)),
                ('zipcode', models.IntegerField(db_column='zipCode')),
                ('email', models.CharField(max_length=64)),
                ('lealperson', models.CharField(db_column='lealPerson', max_length=16)),
                ('delegate', models.CharField(max_length=16)),
                ('delegate_resume', models.TextField()),
                ('units_situation', models.CharField(blank=True, null=True, max_length=64)),
                ('units_time', models.DateTimeField(blank=True, null=True)),
                ('units_count', models.IntegerField(blank=True, null=True)),
                ('units_tech', models.IntegerField(blank=True, null=True)),
                ('units_hightitle', models.IntegerField(blank=True, db_column='units_highTitle', null=True)),
                ('units_midtitle', models.IntegerField(blank=True, db_column='units_midTitle', null=True)),
                ('units_turnover1', models.IntegerField(blank=True, null=True)),
                ('units_turnover2', models.IntegerField(blank=True, null=True)),
                ('units_turnover3', models.IntegerField(blank=True, null=True)),
                ('mainproduct', models.CharField(blank=True, null=True, db_column='mainProduct', max_length=255)),
                ('intention', models.CharField(blank=True, null=True, max_length=64)),
                ('unitscomments', models.CharField(blank=True, null=True, db_column='unitsComments', max_length=64)),
                ('isok', models.CharField(blank=True, null=True, db_column='isOK', max_length=64)),
            ],
            options={
                'db_table': 'register',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', primary_key=True, auto_created=True)),
                ('username', models.CharField(max_length=50)),
                ('UploadFiles', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
