# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('autoid', models.AutoField(primary_key=True, serialize=False, db_column='autoID')),
                ('userid', models.CharField(max_length=64, db_column='userID')),
                ('userpsd', models.CharField(max_length=64, db_column='userPsd')),
                ('name', models.CharField(max_length=16)),
                ('sex', models.CharField(max_length=16, null=True, blank=True)),
                ('birthday', models.DateField(null=True, blank=True)),
                ('hometown', models.CharField(max_length=64, null=True, blank=True)),
                ('nation', models.CharField(max_length=64, null=True, blank=True)),
                ('party', models.CharField(max_length=64, null=True, blank=True)),
                ('photo', models.FileField(upload_to='personalupload/')),
                ('department', models.CharField(max_length=64)),
                ('job', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('postcode', models.IntegerField()),
                ('gradschool', models.CharField(max_length=64, db_column='gradSchool')),
                ('gradtime', models.DateField(db_column='gradTime')),
                ('major', models.CharField(max_length=64)),
                ('health', models.CharField(max_length=64, null=True, blank=True)),
                ('highestdegree', models.CharField(max_length=64, db_column='highestDegree')),
                ('techtitle', models.CharField(max_length=64, null=True, blank=True, db_column='techTitle')),
                ('email', models.CharField(max_length=64)),
                ('phone_depart', models.IntegerField(null=True, blank=True)),
                ('phone_personal', models.IntegerField()),
                ('phone_home', models.IntegerField(null=True, blank=True)),
                ('phone_fax', models.IntegerField(null=True, blank=True)),
                ('now_major', models.CharField(max_length=64)),
                ('speciality', models.CharField(max_length=64, null=True, blank=True)),
                ('workyears', models.IntegerField(null=True, blank=True, db_column='workYears')),
                ('language', models.CharField(max_length=64, null=True, blank=True)),
                ('language_level', models.CharField(max_length=64, null=True, blank=True)),
                ('description_job', models.CharField(max_length=255, null=True, blank=True, db_column='Description_job')),
                ('description_works', models.CharField(max_length=255, null=True, blank=True, db_column='Description_works')),
                ('isverify', models.IntegerField(null=True, blank=True, db_column='isVerify')),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organzation',
            fields=[
                ('autoid', models.AutoField(primary_key=True, serialize=False, db_column='autoID')),
                ('orgid', models.IntegerField(db_column='orgID')),
                ('orgpsd', models.CharField(max_length=45, db_column='orgPsd')),
                ('orgname', models.CharField(max_length=45, db_column='orgName')),
                ('orgcontact', models.CharField(max_length=45, db_column='orgContact')),
                ('orgphone', models.CharField(max_length=45, db_column='orgPhone')),
                ('orgfax', models.CharField(max_length=45, null=True, blank=True, db_column='orgFax')),
                ('orgaddress', models.CharField(max_length=45, null=True, blank=True, db_column='orgAddress')),
                ('orgpostcode', models.CharField(max_length=45, null=True, blank=True, db_column='orgPostcode')),
                ('orgemail', models.CharField(max_length=45, null=True, blank=True, db_column='orgEmail')),
                ('orglrname', models.CharField(max_length=45, null=True, blank=True, db_column='orgLRName')),
                ('orglrbirthday', models.DateField(null=True, blank=True, db_column='orgLRBirthday')),
                ('orglrtitle', models.CharField(max_length=45, null=True, blank=True, db_column='orgLRTitle')),
                ('orglreducation', models.CharField(max_length=45, null=True, blank=True, db_column='orgLREducation')),
                ('orglrphone', models.CharField(max_length=45, null=True, blank=True, db_column='orgLRPhone')),
                ('orglrhomephone', models.CharField(max_length=45, null=True, blank=True, db_column='orgLRHomephoe')),
                ('orglremail', models.CharField(max_length=45, null=True, blank=True, db_column='orgLREmail')),
                ('orgrname', models.CharField(max_length=45, null=True, blank=True, db_column='orgRName')),
                ('orgrbirthday', models.CharField(max_length=45, null=True, blank=True, db_column='orgRBirthday')),
                ('orgrtitle', models.CharField(max_length=45, null=True, blank=True, db_column='orgRTitle')),
                ('orgreducation', models.CharField(max_length=45, null=True, blank=True, db_column='orgREducation')),
                ('orgrphone', models.CharField(max_length=45, null=True, blank=True, db_column='orgRPhone')),
                ('orgrhomephone', models.CharField(max_length=45, null=True, blank=True, db_column='orgRHomephoe')),
                ('orgremail', models.CharField(max_length=45, null=True, blank=True, db_column='orgREmail')),
                ('orgresume', models.FileField(upload_to='orgupload/')),
                ('orgdetail', models.TextField(null=True, blank=True, db_column='orgDetail')),
                ('establishtime', models.DateField(null=True, blank=True, db_column='establishTime')),
                ('totalworkers', models.IntegerField(null=True, blank=True, db_column='totalWorkers')),
                ('techworkers', models.IntegerField(null=True, blank=True, db_column='techWorkers')),
                ('hightitle', models.IntegerField(null=True, blank=True)),
                ('midletitle', models.IntegerField(null=True, blank=True)),
                ('revenueoneyearago', models.IntegerField(null=True, blank=True, db_column='revenueOneyearAgo')),
                ('revenuetwoyearago', models.IntegerField(null=True, blank=True, db_column='revenueTwoyearAgo')),
                ('revenuethreeyearago', models.IntegerField(null=True, blank=True, db_column='revenueThreeyearAgo')),
                ('mainproduct', models.CharField(max_length=255, null=True, blank=True, db_column='mainProduct')),
                ('wanttitle', models.CharField(max_length=255, null=True, blank=True, db_column='wantTitle')),
                ('isagree', models.CharField(max_length=45, null=True, blank=True, db_column='isAgree')),
                ('isverfity', models.CharField(max_length=45, null=True, blank=True, db_column='isVerfity')),
            ],
            options={
                'db_table': 'organzation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('autoid', models.IntegerField(primary_key=True, serialize=False, db_column='autoID')),
                ('memberid', models.IntegerField(db_column='memberID')),
                ('units', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=64)),
                ('tel', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('address', models.CharField(max_length=64)),
                ('zipcode', models.IntegerField(db_column='zipCode')),
                ('email', models.CharField(max_length=64)),
                ('lealperson', models.CharField(max_length=16, db_column='lealPerson')),
                ('delegate', models.CharField(max_length=16)),
                ('delegate_resume', models.TextField()),
                ('units_situation', models.CharField(max_length=64, null=True, blank=True)),
                ('units_time', models.DateTimeField(null=True, blank=True)),
                ('units_count', models.IntegerField(null=True, blank=True)),
                ('units_tech', models.IntegerField(null=True, blank=True)),
                ('units_hightitle', models.IntegerField(null=True, blank=True, db_column='units_highTitle')),
                ('units_midtitle', models.IntegerField(null=True, blank=True, db_column='units_midTitle')),
                ('units_turnover1', models.IntegerField(null=True, blank=True)),
                ('units_turnover2', models.IntegerField(null=True, blank=True)),
                ('units_turnover3', models.IntegerField(null=True, blank=True)),
                ('mainproduct', models.CharField(max_length=255, null=True, blank=True, db_column='mainProduct')),
                ('intention', models.CharField(max_length=64, null=True, blank=True)),
                ('unitscomments', models.CharField(max_length=64, null=True, blank=True, db_column='unitsComments')),
                ('isok', models.CharField(max_length=64, null=True, blank=True, db_column='isOK')),
            ],
            options={
                'db_table': 'register',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('username', models.CharField(max_length=50)),
                ('UploadFiles', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
